### ISSUE TITLE
Is this package support Stage 2 of Zatca?

### ISSUE THREAD

**Issue by aoradev3** [mPhpMaster/laravel-zatca#2]
Hello Developers,
I already used another package for Zatca. But that does not support Stage 2. And May be they won't come with upgrade. Can you please reply that Your package does support Stage 2 or not?

https://zatca.gov.sa/en/E-Invoicing/PreparingYourBusiness/Phase2/Pages/default.aspx

**Comment by mPhpMaster** [comment]
> Stage 2

Hey bro, Stage 2 is an integration with ZATCA throw their SDK, Doesn't effect the QR generator or the generated voucher for Stage 1.
So the QR remain as it is. use what ever package you like.
